# Generated by Django 2.0.5 on 2018-08-27 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allnbateamslist',
            options={},
        ),
        migrations.AlterModelOptions(
            name='seasons',
            options={},
        ),
        migrations.AlterModelOptions(
            name='teamalias',
            options={},
        ),
        migrations.AlterModelOptions(
            name='teams',
            options={},
        ),
    ]
